name: Test Terraform Actions Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform_tests:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/.github/workflows/standard-pipeline.yml@main
    with:
      working-directory: "."
      terraform-version: "1.15.0"
      github-environment: "test-ops-tooling"
      state-bucket: "core-cloud-sonarqube-tf-module-test"
      state-dynamodb-table: "core-cloud-sonarqube-tf-module-test-table-tflock"
      role-to-assume: "cc-bootstrap-tooling-resources-terragrunt-plan-role"
    secrets:
      account_id: ${{ secrets.ACCOUNT_ID }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
