name: Test Terraform Actions Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform_tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/init@main
        with:
          working-directory: "."
          terraform-version: "1.15.0"
          github-environment: "test-ops-tooling"
          state-bucket: "core-cloud-sonarqube-tf-module-test"
          state-dynamodb-table: "core-cloud-sonarqube-tf-module-test-table-tflock"
          role-to-assume: "cc-bootstrap-tooling-resources-terragrunt-plan-role"
          account_id: ${{ secrets.ACCOUNT_ID }}

      - name: Terraform Fmt
        id: quality-checks
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/fmt@main
        with:
          working-directory: 2."

      - name: Terraform Validate
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/validate@main
        with:
          working-directory: "."
          terraform-version: "1.15.0"

      - name: Terraform Test
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/test@main
        with:
          working-directory: "."
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-token:  ${{ secrets.SONAR_TOKEN }}